### ISSUE TITLE
Subtle Timestamp Bug

### ISSUE THREAD

**Issue by samuelvanderwaal** [pegnet/fat-py#1]
I ran across this bug in my code so wanted to make sure you were aware of it. This code, from the `fat2` package `TransactionBatch` class line 101, may not be doing what you expect:

    timestamp: str = str(int(datetime.datetime.utcnow().timestamp()))

I expected this to get a timestamp in UTC of the current time but that's incorrect, because of how Python's `datetime` handles timezones. The method `utcnow()` creates a naive datetime object even though it's the current time in UTC. Because there's no timezone, when you call `timestamp()` on it, that method assumes you've given it a datetime object representing local/system time. This will give you a timestamp that is in the future however many hours you are behind UTC (in my case that's eight hours).  

See the note in the `datetime.timestamp()` documentation:

![Selection_005](https://user-images.githubusercontent.com/1684605/67820522-75ba4900-fa6e-11e9-910b-f3a799546d0b.png)

https://docs.python.org/3/library/datetime.html

It looks like the preferred way to solve this is to import the `timezone` library and then use:

`datetime.datetime.now(timezone.utc)` to create a timezone aware datetime object and then you can call timestamp on that:

`datetime.datetime.now(timezone.utc).timestamp()`

![Selection_006](https://user-images.githubusercontent.com/1684605/67821049-8370ce00-fa70-11e9-8ecd-aa3653a218d8.png)

**Comment by samuelvanderwaal** [comment]
@sambarnes Feel free to close this or I can; I just want to make sure you've seen it.

**Comment by sambarnes** [comment]
Thanks for bringing it up, python's datetime package is notoriously bad with utc timestamps. Tagging @sanchopansa here too if he thinks this should be taken care of.

I have little personal interest in pegnet so I am no longer maintaining this repository.

**Comment by sanchopansa** [comment]
Thanks @samuelvanderwaal for bringing this up!

It is indeed a mess to deal with UTC timestamps as @sambarnes mentioned as well. I remember hitting a lot of similar problems a while ago on a different project.

I will open a PR shortly that addresses the issue.
